# Generated by Django 4.2.4 on 2023-08-05 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('publishedDate', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('pageCount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('categories', models.JSONField(blank=True, null=True)),
                ('averageRating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('maturityRating', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('publicDomain', models.BooleanField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Copies')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbns', models.JSONField(default=list)),
                ('card_id', models.CharField(max_length=50, verbose_name='Library Card Number')),
            ],
        ),
    ]
