# Generated by Django 4.2.4 on 2023-08-05 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkedOut',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Checked Out'),
        ),
    ]
