# Generated by Django 4.2.4 on 2024-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0002_book_checkedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
