# Generated by Django 4.2.4 on 2024-06-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0003_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
