# Generated by Django 4.2.4 on 2024-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0004_alter_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isbns',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
