# Generated by Django 4.2.4 on 2024-06-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0005_alter_user_isbns'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_image',
            field=models.FileField(blank=True, null=True, upload_to='book_isbn_images/'),
        ),
    ]
