# Generated by Django 4.2.4 on 2024-06-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0010_user_card_id_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
