# Generated by Django 4.2.4 on 2024-06-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0013_alter_book_isbn_alter_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
