# Generated by Django 4.2.4 on 2024-06-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0014_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
