# Generated by Django 4.2.4 on 2024-07-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0017_alter_book_isbn_image_alter_user_card_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_image',
            field=models.ImageField(blank=True, null=True, upload_to='data/book_isbn_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='data/card_id_images/'),
        ),
    ]
