# Generated by Django 4.2.4 on 2024-07-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0018_alter_book_isbn_image_alter_user_card_id_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Bookend', max_length=100)),
            ],
        ),
    ]
