# Generated by Django 4.2.4 on 2024-07-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0019_appmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='data/book_isbn_images/'),
        ),
    ]
