# Generated by Django 4.2.4 on 2024-07-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0020_book_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_image',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/book_isbn_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/book_cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/card_id_images/'),
        ),
    ]
