# Generated by Django 4.2.4 on 2024-11-06 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0023_stats_book_date_added_book_total_checked_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkout_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='averageRating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkedOut',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Checked out'),
        ),
        migrations.AlterField(
            model_name='book',
            name='maturityRating',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Maturity rating'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pageCount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Page count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicDomain',
            field=models.BooleanField(blank=True, null=True, verbose_name='Public domain'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_checked_out',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lifetime checked out'),
        ),
    ]
