# Generated by Django 4.2.4 on 2025-02-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookend', '0025_alter_user_checkout_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='checkout_history',
            field=models.JSONField(default=list),
        ),
    ]
